# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations
from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field
from typing import Any
from enum import Enum, StrEnum


class StartupCaptureConfig(BaseModel):
    enabled: bool = Field(
        ..., description="When true, the daemon opens a diagnostics capture at boot."
    )
    duration_seconds: int = Field(
        ...,
        description="Duration of the boot-time capture. Zero falls back to the default (300 s).",
        ge=0,
        le=1800,
    )
    anonymise: bool = Field(
        ...,
        description="Whether to hash device-address-shaped values in the recorded archive.",
    )


class ExportedConfiguration(BaseModel):
    version: str = Field(
        ..., description='Serialisation format version. Always "1.0".', examples=["1.0"]
    )
    exported_at: AwareDatetime = Field(
        ..., description="UTC instant at which the snapshot was taken."
    )
    central_name: str | None = Field(
        None,
        description="CCU name that owns this channel (multi-CCU safe). Empty for single-CCU setups.\n",
    )
    device_address: str = Field(
        ..., description='Serial / address of the parent device, e.g. "0001ABCD".'
    )
    model: str = Field(..., description='Device model string, e.g. "HmIP-eTRV-2".')
    channel_address: str = Field(
        ...,
        description='Full channel address including channel index, e.g. "0001ABCD:1".',
    )
    channel_type: str = Field(
        ..., description='Functional type of the channel, e.g. "CLIMATE_TRANSCEIVER".'
    )
    paramset_key: str = Field(
        ...,
        description='Name of the exported paramset, typically "MASTER" or "VALUES".',
    )
    values: dict[str, Any] = Field(
        ..., description="Parameter name → value mapping captured at export time."
    )


class Priority(StrEnum):
    critical = "critical"
    high = "high"
    default = "default"
    low = "low"


class CustomDPInvokeRequest(BaseModel):
    params: dict[str, Any] | None = Field(
        None, description="Operation-specific parameters (category-dependent)."
    )
    priority: Priority | None = None


class CustomDPSummary(BaseModel):
    name: str = Field(
        ...,
        description="Wire identity of the Custom-DP. The bare parameter name\n(`LEVEL`, `BUTTON_LOCK`) when it is unique on the device;\n`PARAM@<channel>` (e.g. `LEVEL@5`) when a profile channel\ngroup materialises the same parameter on multiple channels.\nRound-trip this value verbatim into `GET/POST …/cdps/{name}`.\n",
    )
    category: str
    channel_no: int
    supported_operations: list[str]
    kind: str | None = Field(
        None,
        description="Stable widget hint derived from the concrete Custom-DP\ntype — e.g. `light`, `light_color`, `light_color_temp`,\n`light_fixed_color`, `light_rgbw`, `cover_blind`,\n`cover_garage`, `climate_hmip`, `climate_rf`,\n`climate_simple`, `lock`, `siren`, `switch`,\n`text_display`. Drives the SPA's CDP-aware widget\nselection (ADR 0016). Empty when the kind classifier\ndoes not recognise the Custom-DP type.\n",
    )
    channels: list[int] | None = Field(
        None,
        description="CCU channels this Custom-DP is materialised on. The\ncurrent implementation always contains exactly the\nprimary channel (matching `channel_no`); future\niterations may expand to include sibling channels\npulled in via the `RebasedChannelGroupConfig`\nmechanism.\n",
    )
    capabilities: dict[str, bool] | None = Field(
        None,
        description="Flat string→bool map of optional features the device\nsupports — e.g. `dimmable`, `color`, `color_temp`,\n`effects`, `tilt`, `boost`, `away`. Mirrors the\nper-category Capability struct from\n`internal/model/custom/mixins.go`.\n",
    )
    config: dict[str, Any] | None = Field(
        None,
        description="Static configuration block from the Custom-DP — temperature\nbounds (`min_temp`, `max_temp`, `temp_step`), available\n`hvac_modes`, available `preset_modes`, capability hints.\nPopulated from the DP's `Config()` ([payload.Source]).\nLets clients render kind-specific choice lists and seed\nHA entity capabilities without a second round-trip.\n",
    )
    state: dict[str, Any] | None = Field(
        None,
        description="Live state snapshot from the Custom-DP — the same semantic\nkeys the WS `custom_data_point.state_changed` event carries\n(`is_locked`, `hvac_mode`, `brightness`, …). Lets clients\nseed entity state at bootstrap without one extra\nround-trip per CDP.\n",
    )
    unique_id: str = Field(
        ...,
        description="Canonical loom routing key for this Custom-DP — the same\nvalue the WS `custom_data_point.state_changed` payload\ncarries. Lets a client build its entity registry from the\nsummary without recomputing the key. Always present and non-empty: a central serves no entity until its CCU serial (the central-id slot of the key) is resolved by the bring-up readiness gate.\n",
    )


class Type(Enum):
    https___openccu_loom_dev_errors_validation = (
        "https://openccu-loom.dev/errors/validation"
    )
    https___openccu_loom_dev_errors_not_found = (
        "https://openccu-loom.dev/errors/not_found"
    )
    https___openccu_loom_dev_errors_conflict = (
        "https://openccu-loom.dev/errors/conflict"
    )
    https___openccu_loom_dev_errors_unauthorized = (
        "https://openccu-loom.dev/errors/unauthorized"
    )
    https___openccu_loom_dev_errors_forbidden = (
        "https://openccu-loom.dev/errors/forbidden"
    )
    https___openccu_loom_dev_errors_unsupported = (
        "https://openccu-loom.dev/errors/unsupported"
    )
    https___openccu_loom_dev_errors_rate_limited = (
        "https://openccu-loom.dev/errors/rate_limited"
    )
    https___openccu_loom_dev_errors_internal = (
        "https://openccu-loom.dev/errors/internal"
    )
    https___openccu_loom_dev_errors_bad_request = (
        "https://openccu-loom.dev/errors/bad_request"
    )
    https___openccu_loom_dev_errors_service_unready = (
        "https://openccu-loom.dev/errors/service_unready"
    )
    https___openccu_loom_dev_errors_upstream_unavailable = (
        "https://openccu-loom.dev/errors/upstream_unavailable"
    )


class Code(StrEnum):
    validation = "validation"
    not_found = "not_found"
    conflict = "conflict"
    unauthorized = "unauthorized"
    forbidden = "forbidden"
    unsupported = "unsupported"
    rate_limited = "rate_limited"
    internal = "internal"
    bad_request = "bad_request"
    service_unready = "service_unready"
    upstream_unavailable = "upstream_unavailable"


class Error(BaseModel):
    field: str | None = None
    reason: str | None = None
    min: Any | None = None
    max: Any | None = None


class Problem(BaseModel):
    type: Type = Field(
        ...,
        description="Stable URI for one of the canonical problem kinds. All\nURIs share the base `https://openccu-loom.dev/errors/`\nand the trailing segment matches the `code` enum below.\nThe base URI is a stable identifier, not a fetchable\nresource — it is not guaranteed to resolve to a document.\n",
    )
    title: str
    status: int
    detail: str | None = None
    instance: str | None = None
    code: Code | None = Field(
        None,
        description="Short tag (also surfaced as the `X-Problem-Code` response header).",
    )
    errors: list[Error] | None = None


class Info(BaseModel):
    version: str = Field(..., description="Daemon build version (semver).")
    commit: str
    build_date: str
    addon_build: bool = Field(
        ...,
        description="True when this binary was built as the CCU/RaspberryMatic\nadd-on (it then runs on the CCU itself). False for the\nstandalone binary, Docker image, and HA add-on builds.\n",
    )
    uptime: str
    started_at: AwareDatetime
    api_version: str = Field(
        ...,
        description="North-bound contract version (semver). Bumps independently\nof `version`. Minor bumps add backwards-compatible\ncapabilities; major bumps remove or rename existing\npayload fields, scopes, or capabilities.\n",
    )
    schema_digest: str = Field(
        ...,
        description="Canonical digest of the contract assets (openapi.yaml,\nwsapi.json, schemas/enums.json, schemas/types.json) this\nbinary was built from, e.g. `sha256:ab12…`. Generated\nclient type packages carry the same value; a client\ncompares the two at connect time to verify its types\nmatch the daemon build exactly. Equality means exact\ncontract identity; inequality means the types were\ngenerated from a different build (not necessarily an\nincompatible one — use `api_version` for compatibility\nreasoning).\n",
        examples=[
            "sha256:0c63c1e3a9f0b14d2e5b7a86c14d9b21f0aa3340be71f5c6d8e92041ab57cd10"
        ],
    )
    capabilities: list[str] = Field(
        ...,
        description="Runtime feature set. Always-on entries:\n`rest.v1`, `ws.broadcasts.v1`, `errors.problem_details.v1`.\nConditional entries surface only when configured:\n`mqtt.discovery.v1`, `matter.bridge.v1`, `auth.oidc.v1`.\n\nOpen-ended on purpose: the daemon may advertise additional\ncapabilities (e.g. `system.restart.supervised.v1`, `mcp.v1`)\nas features are added. Clients MUST treat this as a forward-\ncompatible string set and ignore values they do not recognise\n— never reject an `Info` payload because of an unknown entry.\n",
    )


class Phase(StrEnum):
    unknown = "unknown"
    waiting_for_ccu = "waiting_for_ccu"
    loading_hub = "loading_hub"
    loading_devices = "loading_devices"
    ready = "ready"


class Readiness(BaseModel):
    phase: Phase = Field(..., description="Current bring-up phase of the central.")
    ready: bool = Field(
        ..., description="True once the southbound bring-up has latched complete."
    )
    interfaces_loaded: int = Field(
        ..., description="Number of interfaces wired so far during device loading."
    )
    interfaces_total: int = Field(
        ..., description="Total number of configured interfaces to wire."
    )


class SystemCCUEntry(BaseModel):
    name: str = Field(
        ...,
        description="Daemon-local scoping identifier. Equal to `CentralRow.name`\nand to the `central` field in WS / payload envelopes; unique\nper daemon.\n",
    )
    host: str
    available: bool
    model: str | None = None
    version: str | None = None
    hostname: str | None = None
    serial: str | None = None
    url: AnyUrl | None = None
    is_ha_app: bool
    configured_interfaces: list[str]
    readiness: Readiness = Field(
        ...,
        description='Where the central is in its readiness-gated southbound\nbring-up, so the SPA can distinguish "still initializing"\nfrom "offline".\n',
    )


class Status(StrEnum):
    healthy = "healthy"
    degraded = "degraded"
    unhealthy = "unhealthy"
    unknown = "unknown"


class Component(BaseModel):
    name: str
    status: str
    note: str | None = None
    note_key: str | None = Field(
        None,
        description="i18n catalogue key for the localized display of a static note; absent for interpolated notes (render note verbatim).",
    )
    recorded_at: AwareDatetime


class Health(BaseModel):
    status: Status
    components: list[Component]


class Central(BaseModel):
    name: str | None = None
    host: str | None = None
    interfaces: list[str] | None = None


class CallbackPorts(BaseModel):
    xmlrpc: int | None = None
    binrpc: int | None = None


class ConfigSnapshot(BaseModel):
    locale: str | None = None
    centrals: list[Central] | None = None
    callback_ports: CallbackPorts | None = None
    features: dict[str, bool] | None = None
    extras: dict[str, str] | None = None
    policies: dict[str, bool] | None = Field(
        None,
        description="Static daemon-side behaviour switches. Keys are stable;\nvalues reflect the current effective policy. See the\n`/config` path-level description for the canonical key\ncatalogue.\n",
    )


class UpdateStatus(StrEnum):
    up_to_date = "up_to_date"
    update_available = "update_available"
    installing = "installing"


class DeviceSummary(BaseModel):
    address: str
    central: str | None = Field(
        None,
        description="CCU this device belongs to (multi-central grouping). Omitted\nfor backends that report no owning central.\n",
    )
    interface: str
    interface_id: str
    ise_id: int | None = Field(
        None,
        description="CCU-internal numeric device id. Lets clients that address\ndevices by ISE_ID (e.g. the HA rename-by-ise_id path) map back\nto the device address. Absent when the backend reports none.\n",
    )
    model: str
    model_label: str | None = Field(
        None,
        description="Localised, human-readable device-type label. Empty when no\ntranslation exists; consumers fall back to the raw `model`.\n",
    )
    model_icon: str | None = Field(
        None, description="Icon identifier for the device model. Empty when none."
    )
    sub_model: str | None = None
    name: str
    manufacturer: str | None = None
    product_group: str | None = None
    available: bool
    channels_count: int
    updatable: bool = Field(
        ...,
        description='Device *supports* firmware updates (CCU UPDATABLE capability) —\nNOT whether one is pending. Use update_available for the\n"update available" indicator.\n',
    )
    update_available: bool = Field(
        ...,
        description="An installable firmware update is actually pending: the gated\nlatest version differs from the installed one (image already\ndelivered for HmIP-RF / available for BidCos). A newer firmware\nthe CCU merely knows about but has not delivered does NOT set this.\n",
    )
    update_status: UpdateStatus | None = Field(
        None,
        description="Daemon-derived firmware-update verdict collapsing the raw CCU\nfirmware phase and update_available signal, so a client renders\nthe update entity without carrying the phase-classification sets.\nOmitted when the device reports no firmware information.\n",
    )
    rooms: list[str] | None = None
    functions: list[str] | None = Field(
        None, description='Resolved "Gewerke" (function) labels for the device.'
    )
    master_pushes_config_pending: bool = Field(
        ...,
        description="True when the device's interface delivers reliable CONFIG_PENDING\nevents on MASTER writes (HmIP-RF, HmIP-Wired). The SPA then waits\nfor the true→false transition before refreshing MASTER. False for\nBidCos-*, VirtualDevices, CUxD — those rely on the save-path\nreload because CONFIG_PENDING never fires (or fires unreliably).\n",
    )
    has_sub_devices: bool = Field(
        ...,
        description="True when the device should be split into multiple logical\nsub-devices for northbound presentation. The SPA's CdpTilesPanel\nuses this flag to switch from a flat tile grid to per-group\nsections.\n",
    )


class DeviceList(BaseModel):
    items: list[DeviceSummary]
    page: int
    per_page: int
    total: int


class Firmware(BaseModel):
    Current: str | None = None
    Available: str | None = None
    Updatable: bool | None = None
    UpdateState: str | None = None


class Availability(BaseModel):
    IsReachable: bool | None = None
    LastUpdated: AwareDatetime | None = None
    BatteryLevel: int | None = None
    LowBattery: bool | None = None
    SignalStrength: int | None = None


class ChannelSummary(BaseModel):
    address: str
    number: int
    name: str | None = Field(
        None, description="User-defined channel name. Empty when none is set."
    )
    category: str | None = Field(
        None,
        description="OCCU channel-type string (same value as `type`), exposed under\nits own key so consumers can route on channel purpose without\nparsing the `type` string.\n",
    )
    type: str | None = Field(
        None, description="OCCU channel-type string (e.g. ENERGIE_METER_TRANSMITTER)."
    )
    type_label: str | None = Field(
        None,
        description="Localised, human-readable channel-type label resolved through\nthe OCCU channel_types table. Empty when no translation exists;\nconsumers fall back to the raw `type`.\n",
    )
    paramset_key: str
    paramset_keys: list[str] | None = Field(
        None,
        description='Paramsets this channel actually exposes — "VALUES" when it has\nvalue data points and "MASTER" when it has master (config) data\npoints. The config-panel / HA drop-in uses this to offer the\nright paramset tabs.\n',
    )
    data_points_count: int
    custom_dp_name: str | None = Field(
        None,
        description="Stable name of the Custom-DP this channel is attached to.\nEmpty when the channel is not owned by any CDP. Lets the\nSPA's CDP-first Übersicht view (ADR 0016) filter channels\nthat are already represented by a CDP tile.\n",
    )
    group_no: int | None = Field(
        None,
        description="Channel-group number this channel belongs to (the group\nmaster's channel number). Omitted when the channel is not\npart of any channel group.\n",
    )
    is_group_master: bool | None = Field(
        None,
        description="True when this channel is the master of its channel group\n(`group_no == number`). Only present alongside `group_no`.\n",
    )
    is_in_multi_group: bool | None = Field(
        None,
        description="True when the channel's group has more than one member —\ni.e. the channel participates in the parent device's\nsub-device split. Singleton groups omit the flag.\n",
    )
    sub_device_name: str | None = Field(
        None,
        description="Resolved sub-device label for the channel's group (the\ngroup master's name with device-name/number fallbacks).\nOnly present for multi-member groups.\n",
    )
    room: str | None = Field(
        None,
        description="The channel's single resolved room with the group-master\nfallback applied. Empty when no unique room can be\nresolved. External clients use it as the suggested area of\nthe channel group's sub-device.\n",
    )
    functions: list[str] | None = Field(
        None,
        description='The channel\'s resolved "Gewerke" (function) labels — the\nchannel-level twin of `DeviceSummary.functions`. Lets clients\nmap functions at channel granularity instead of folding them\nup to the device. Omitted when the channel carries no function\nassignment.\n',
    )
    is_custom_dp_primary: bool | None = Field(
        None,
        description='True when the channel owns a Custom-DP AND is the primary\n(group-master) channel of its group — the daemon-derived\n"device primary channel" marker. Omitted when neither\ncondition holds.\n',
    )


class MQTTReloadResponse(BaseModel):
    reloaded: bool = Field(
        ...,
        description="Always true on success; the 503 path returns a problem+json document instead.",
    )
    took_ms: int = Field(
        ..., description="Wall-clock duration of the swap in milliseconds."
    )


class Kind(StrEnum):
    global_ = "global"
    central = "central"
    interface = "interface"
    device = "device"


class CacheClearRequest(BaseModel):
    kind: Kind = Field(
        ...,
        description="Breadth of the clear. `central`/`interface`/`device` require\nthe matching identifier fields at or below their level.\n",
    )
    central: str | None = Field(
        None, description="Central name. Required for kind central/interface/device."
    )
    interface: str | None = Field(
        None, description="Interface id. Required for kind interface/device."
    )
    device: str | None = Field(
        None, description="Device address. Required for kind device."
    )


class Scope(BaseModel):
    Kind: str | None = None
    Central: str | None = None
    Interface: str | None = None
    Device: str | None = None


class CacheClearReport(BaseModel):
    scope: Scope = Field(..., description="The resolved scope the clear ran against.")
    devices: int = Field(
        ...,
        description="Device-description rows removed (-1 when the store does not report a count).",
    )
    paramsets: int = Field(..., description="Paramset-description rows removed.")
    values: int = Field(
        ...,
        description="Persistent VALUES-cache rows removed (-1 for device-scoped deletes).",
    )
    master: int = Field(
        ...,
        description="Persisted MASTER-value rows removed (-1 for device-scoped deletes).",
    )
    centrals_reinit: list[str] = Field(
        ..., description="Centrals that were re-initialized through the boot path."
    )
    errors: list[str] | None = Field(
        None,
        description="Per-store errors collected during the clear; present only when the clear partially failed.",
    )


class ValuesCacheStats(BaseModel):
    rows: int = Field(..., description="Current row count in the cache.")
    value_json_bytes: int = Field(
        ..., description="Sum of value_json byte sizes across all rows."
    )
    restored_rows: int = Field(
        ..., description="Cumulative rows successfully restored since process start."
    )
    cast_failures: int = Field(
        ...,
        description="Cumulative entries whose cached value could not be coerced into the data point's static type.",
    )
    gc_rows_deleted: int = Field(
        ...,
        description="Cumulative rows removed by the dead-row GC since process start.",
    )
    flush_batches: int = Field(
        ...,
        description="Cumulative SaveBatch transactions committed since process start.",
    )
    flushed_entries: int = Field(
        ..., description="Cumulative entries written across all SaveBatch transactions."
    )


class Source(StrEnum):
    unobserved = "unobserved"
    cache = "cache"
    live = "live"
    stale = "stale"


class Operations(BaseModel):
    read: bool
    write: bool
    event: bool


class UiHint(BaseModel):
    icon: str = Field(
        ..., description='Material Design Icons token, e.g. "mdi:thermometer".'
    )
    semantic: str = Field(
        ...,
        description='Stable token used by the composer to group readouts\nof the same physical quantity into one bucket\n(e.g. "temperature", "particulate", "motion").\n',
    )
    state_color_rule: str | None = Field(
        None,
        description='Named threshold rule the SPA looks up in its rule\nregistry to colour the readout (e.g. "temp_heat",\n"alarm_active", "signal_weak"). Empty when no rule.\n',
    )


class DataPointSummary(BaseModel):
    parameter: str
    parameter_label: str | None = Field(
        None,
        description='Ready-to-display caption for the parameter row: the\nlocale-aware channel-typed translation when one exists,\notherwise the title-cased parameter (`RSSI_DEVICE` →\n`Rssi Device`). Always non-empty; clients render it\nverbatim instead of deriving their own fallback. Unlike\n`translated_name` it carries text even when\n`label_omitted` is true — the "primary parameter"\ncollapse is an entity-naming concern, row captions keep\ntheir label.\n',
    )
    value: Any | None = None
    observed: bool
    modified_at: AwareDatetime | None = Field(
        None,
        description="When the value last changed on the CCU. RFC3339Nano,\nUTC. Equivalent to `last_changed_at` (kept for\ncache-friendly naming alongside `last_seen_at`).\n",
    )
    source: Source | None = Field(
        None,
        description="Wire-side lifecycle token. See ADR 0018.\n- unobserved: never seen any value\n- cache: restored from persistent cache at boot, awaiting live event\n- live: last value confirmed by CCU push / fetch_all, connection healthy\n- stale: connection lost; value is the last known good\n",
    )
    last_seen_at: AwareDatetime | None = Field(
        None,
        description="When the data point was last observed via any push or\nfetch_all event (cyclic info telegrams included). Advances\neven when the value did not change.\n",
    )
    last_changed_at: AwareDatetime | None = Field(
        None,
        description="When the value actually changed last. Alias of modified_at\nkept under the cache-friendly name.\n",
    )
    value_age_seconds: int | None = Field(
        None,
        description="Pre-computed seconds between last_seen_at and the response\ntime, so the browser does not need to parse the timestamp\non every render.\n",
    )
    operations: Operations
    category: str | None = Field(
        None,
        description='Fine-grained DataPointCategory the daemon derives internally\n("light", "cover", "climate", "sensor", "binary_sensor",\n"switch", …). External clients spawn entities off this instead\nof re-deriving categories from raw paramsets. A change to a\ncategory value is a breaking wire change — see the enum\ncatalogue in assets/schemas/enums.json and ADR 0020. Empty\nonly when the DP does not implement the categorised surface.\n',
    )
    data_point_type: str | None = Field(
        None,
        description='Consumer-facing functional type mapped from category via\nhmenum.CategoryToType ("light", "number", "select", "sensor",\n…). Distinct from `type` (the CCU descriptor primitive); the\ntwo must not be conflated.\n',
    )
    usage: str | None = Field(
        None,
        description='Visibility verdict from the daemon\'s pipeline ("data_point",\n"no_create", "ignored", "ce_primary", "ce_secondary",\n"ce_visible", "event"). Clients skip entity creation for\n"no_create"/"ignored" — the same gate the MQTT discovery\nplane applies; mirrors aiohomematic\'s DataPointUsage.\n',
    )
    translated_name: str | None = Field(
        None,
        description="Locale-aware per-entity name a north-bound consumer (HA via\nMQTT discovery or the REST drop-in) assigns to this data\npoint. Identical to the MQTT discovery `name` field — both\nresolve through the same naming primitive. The parameter\nportion only; HA prepends the device name. Empty when\n`label_omitted` is true.\n",
    )
    label_omitted: bool | None = Field(
        None,
        description='True when the parameter is flagged "primary" in the embedded\ntranslation_custom catalogue (translation key present, value\nempty). Consumers then collapse the entity name to the device\nname alone (MQTT discovery emits `name: null`).\n',
    )
    control: str | None = Field(
        None,
        description="CCU paramset descriptor's CONTROL attribute of the form\nWIDGET_FAMILY.SLOT (e.g. \"HEATING_CONTROL_HMIP.SETPOINT\").\nDrives the SPA's CONTROL-aware widget resolver. See\ndocs/ui/control-widget-concept.md. Empty when the\ndescriptor carries no CONTROL.\n",
    )
    type: str | None = Field(
        None,
        description="CCU descriptor TYPE (BOOL, INTEGER, FLOAT, ENUM, STRING, ACTION).\nSurfaced so the SPA can pick the right widget primitive\nwithout re-reading the paramset descriptor.\n",
    )
    value_list: list[str] | None = Field(
        None,
        description='Ordered enum labels for ENUM-typed parameters\n(e.g. ["BLACK","BLUE","GREEN","TURQUOISE","RED","PURPLE",\n"YELLOW","WHITE"] on HmIP-BSL COLOR). Empty for non-ENUM.\n',
    )
    value_translations: dict[str, str] | None = Field(
        None,
        description="Maps each raw `value_list` entry to its localised display\nstring, resolved through the OCCU `parameter_values_<locale>`\ntable in the request locale. Only entries with an actual\ntranslation are included (an untranslated value is omitted so\nthe client falls back to the raw `value_list` token); absent\nentirely for non-ENUM parameters or when no value translates.\n",
    )
    unit: str | None = Field(
        None,
        description='Descriptor UNIT string ("°C", "% rF", "lx", "Wh", ...)\nas the CCU declares it. Empty when none.\n',
    )
    min: Any | None = None
    max: Any | None = None
    default: Any | None = None
    ui_hint: UiHint | None = Field(
        None,
        description="Daemon-computed UI classification envelope. The SPA's\nAutoTile composer reads the fields verbatim — no JS-side\nclassification runs. See docs/ui/auto-tile-concept.md.\nResolution order in the backend: parameter substring →\nENUM-shape rules → unit table → type fallback. Never\nempty.\n",
    )
    unique_id: str = Field(
        ...,
        description="Canonical loom-namespaced routing key for this data point —\nthe same value the WS `datapoint.value_changed` payload\ncarries. Lets a client build its entity registry from the\nsummary or snapshot without recomputing the key. Always present and non-empty: a central serves no entity until its CCU serial (the central-id slot of the key) is resolved by the bring-up readiness gate.\n",
    )
    additional_information: dict[str, Any] | None = Field(
        None,
        description="Optional enriched model metadata for data points that provide\nit (e.g. the calculated operating-voltage sensor's battery\ntype / quantity / low-voltage limits). Absent for plain scalar\ndata points. Mirrors the optional `additional_information`\nobject on the per-DP MQTT state topic. Additive — existing\nresponses are unchanged.\n",
    )


class UIEventRequest(BaseModel):
    event: str = Field(
        ..., description="Event name (e.g. `device_detail.view_selector`)."
    )
    properties: dict[str, Any] | None = Field(
        None, description="Optional event-specific key/value attributes."
    )


class SetValueRequest(BaseModel):
    value: Any
    priority: Priority | None = None


class WebhookValueRequest(BaseModel):
    central: str | None = Field(
        None,
        description="Optional CCU name. Device addresses are globally unique, so the\nwriter resolves the owning CCU from `address`; `central` is\ninformational.\n",
    )
    address: str = Field(..., description='Channel address, e.g. "0001D3C99C1234:1".')
    parameter: str = Field(
        ..., description='Wire parameter name, e.g. "STATE" or "LEVEL".'
    )
    value: Any
    priority: Priority | None = None


class WebhookProgramRequest(BaseModel):
    central: str | None = Field(
        None,
        description="CCU name. Required when more than one CCU is configured, since\nprogram IDs are not unique across CCUs.\n",
    )
    program: str = Field(..., description="Program ID to run.")


class ProgramSummary(BaseModel):
    central: str | None = Field(
        None, description="CCU this program belongs to (multi-central grouping)."
    )
    id: str
    name: str
    description: str | None = None
    active: bool | None = Field(
        None,
        description="Program enabled state. Omitted when the CCU has not reported it\n(the Go DTO marshals the pointer with omitempty: absent, not null).\n",
    )
    last_executed: str | None = Field(
        None, description="RFC3339 timestamp of the most recent execution."
    )
    is_internal: bool | None = Field(
        None,
        description="True for CCU-internal helper programs (prgEnergyCounter_…,\nTmp_…). Clients skip these for HA entities, mirroring\naiohomematic's DEFAULT_INCLUDE_INTERNAL_PROGRAMS=false.\n",
    )
    enabled_default: bool | None = Field(
        None,
        description="True when the program matched a configured description marker, so\nclients enable its entity by default. Absent/false when no markers\nare configured: the entry is included but disabled by default.\n",
    )
    unique_id: str = Field(
        ...,
        description="Canonical loom routing key for this program — the same value\nthe WS `hub.program_executed` event carries. Lets clients\nbuild their entity registry from the summary without\nrecomputing the key. Always present and non-empty: a central serves no entity until its CCU serial (the central-id slot of the key) is resolved by the bring-up readiness gate.\n",
    )
    channel: str | None = Field(
        None,
        description='Canonical channel address ("ADDR:idx") of the device channel\nthis program is associated with (resolved from a device\nidentifier in the program name). Absent when the program\nbelongs to no device — clients then attach the entity to the\ncentral hub device instead of a physical device.\n',
    )
    device_address: str | None = Field(
        None,
        description='Device part of `channel` (before the ":"). Clients use it to\ngroup the entity under the owning physical device; absent\ntogether with `channel` (entity belongs on the hub card).\n',
    )


class SysvarSummary(BaseModel):
    central: str | None = Field(
        None, description="CCU this system variable belongs to."
    )
    name: str
    description: str | None = None
    unit: str | None = None
    value_type: str
    value: Any | None = None
    observed: bool
    value_list: list[str] | None = None
    min: float | None = Field(
        None, description="Declared lower bound from the CCU Rega response."
    )
    max: float | None = Field(
        None, description="Declared upper bound from the CCU Rega response."
    )
    is_internal: bool | None = Field(
        None,
        description="Mirrors the CCU's isInternal flag. Internal variables back\nCCU bookkeeping; clients skip them for HA entities unless\nopted in (aiohomematic's INTERNAL description marker).\n",
    )
    is_extended: bool | None = Field(
        None,
        description="True when the variable's description carried the extended\nmarker — clients expose the writable entity flavour\n(switch/number/select/text) instead of the read-only default.\n",
    )
    vid: int | None = Field(
        None,
        description="CCU-internal numeric variable ID (ise_id). Stable across\nrenames; clients use it to apply fixed-ID exclusions\n(40 = alarm messages, 41 = service messages — both are\nsurfaced through dedicated hub singletons instead).\n",
    )
    enabled_default: bool | None = Field(
        None,
        description="True when the variable matched a configured description marker, so\nclients enable its entity by default. Absent/false when no markers\nare configured: the entry is included but disabled by default.\n",
    )
    unique_id: str = Field(
        ...,
        description="Canonical loom routing key for this system variable — the\nsame value the WS `hub.sysvar_changed` event carries. Lets\nclients build their entity registry from the summary without\nrecomputing the key. Always present and non-empty: a central serves no entity until its CCU serial (the central-id slot of the key) is resolved by the bring-up readiness gate.\n",
    )
    channel: str | None = Field(
        None,
        description='Canonical channel address ("ADDR:idx") of the device channel\nthis system variable is associated with — either the explicit\nCCU WebUI channel assignment ("Kanalzuordnung") or, failing\nthat, a device identifier resolved from the variable name.\nAbsent when the variable belongs to no device — clients then\nattach the entity to the central hub device instead of a\nphysical device.\n',
    )
    device_address: str | None = Field(
        None,
        description='Device part of `channel` (before the ":"). Clients use it to\ngroup the entity under the owning physical device; absent\ntogether with `channel` (entity belongs on the hub card).\n',
    )


class SysvarSetRequest(BaseModel):
    value: Any


class HistoryBucket(BaseModel):
    ts: AwareDatetime = Field(..., description="Start of the bucket's time span (UTC).")
    avg: float = Field(..., description="Mean of the raw samples in this bucket.")
    min: float = Field(..., description="Minimum raw sample in this bucket.")
    max: float = Field(..., description="Maximum raw sample in this bucket.")
    count: int = Field(
        ..., description="Number of raw samples aggregated into this bucket."
    )


class EnergyBucket(BaseModel):
    ts: AwareDatetime = Field(..., description="Start of the bucket's time span (UTC).")
    consumed_wh: float = Field(
        ...,
        description="ENERGY_COUNTER delta over the bucket, in Wh. Never negative — see `reset`.\n",
    )
    feed_in_wh: float = Field(
        ...,
        description="ENERGY_COUNTER_FEED_IN delta over the bucket, in Wh. Never negative — see `reset`.\n",
    )
    avg_power_w: float = Field(
        ..., description="Mean POWER sample over the bucket, in W."
    )
    peak_power_w: float = Field(
        ..., description="Maximum POWER sample over the bucket, in W."
    )
    reset: bool = Field(
        ...,
        description="True when a cumulative counter went backwards within this bucket (meter reset on re-pair / firmware event); the reported delta is the counter's value at the end of the bucket (energy accumulated since the reset), not a negative delta.\n",
    )


class EnergyDevice(BaseModel):
    address: str = Field(..., description="Bare device address.")
    name: str = Field(
        ..., description="Device display name (falls back to the address when unknown)."
    )
    buckets: list[EnergyBucket]
    total_consumed_wh: float = Field(
        ..., description="Sum of `consumed_wh` across every bucket, in Wh."
    )
    total_feed_in_wh: float = Field(
        ..., description="Sum of `feed_in_wh` across every bucket, in Wh."
    )


class Group(StrEnum):
    hour = "hour"
    day = "day"
    month = "month"


class EnergyResponse(BaseModel):
    group: Group = Field(..., description="Bucket granularity actually used.")
    from_: AwareDatetime = Field(
        ...,
        alias="from",
        description="Inclusive lower bound of the requested range (UTC).",
    )
    to: AwareDatetime = Field(
        ..., description="Exclusive upper bound of the requested range (UTC)."
    )
    devices: list[EnergyDevice]
    total_consumed_wh: float = Field(
        ..., description="Sum of every device's `total_consumed_wh`, in Wh."
    )
    total_feed_in_wh: float = Field(
        ..., description="Sum of every device's `total_feed_in_wh`, in Wh."
    )


class Change(BaseModel):
    parameter: str
    before: Any | None = None
    after: Any | None = None


class AuditEntry(BaseModel):
    central: str | None = Field(
        None,
        description="CCU this entry belongs to, derived best-effort from the device\naddress. Omitted for daemon-wide entries (e.g. CCU management).\n",
    )
    timestamp: AwareDatetime = Field(
        ..., description="UTC time at which the change was recorded."
    )
    user: str | None = Field(
        None,
        description="Authenticated user who triggered the change (empty if unauthenticated).",
    )
    action: str = Field(
        ...,
        description="Stable action tag, e.g. paramset_write, link_add, data_point_write. New values may be added in future releases.\n",
    )
    device_address: str | None = Field(
        None, description="Primary device or channel address, if applicable."
    )
    channel_no: int | None = Field(
        None, description="Channel number within the device, if applicable."
    )
    paramset: str | None = Field(
        None, description="Paramset type (MASTER, VALUES, LINK), if applicable."
    )
    peer: str | None = Field(None, description="Peer address for link operations.")
    parameter: str | None = Field(
        None, description="Parameter name for single-parameter writes."
    )
    note: str | None = Field(
        None,
        description="Free-form context (e.g. profile ID for active_profile changes).",
    )
    changes: list[Change] | None = Field(
        None, description="Per-parameter before/after pairs for paramset writes."
    )


class AlarmMessage(BaseModel):
    central: str | None = Field(
        None, description="CCU this alarm message belongs to (multi-central grouping)."
    )
    id: str
    name: str
    description: str | None = None
    device_name: str | None = None
    address: str | None = Field(
        None,
        description="CCU channel address that generated the alarm. Omitted when\nunavailable (legacy CCUs).\n",
    )
    state_value: str | None = Field(
        None, description="Raw alarm state string from the CCU Rega script."
    )
    timestamp: AwareDatetime
    counter: int
    last_trigger: str | None = None
    display_name: str | None = Field(
        None, description="Human-readable translation of the message code."
    )
    rooms: list[str] | None = None


class ServiceMessage(BaseModel):
    central: str | None = Field(
        None,
        description="CCU this service message belongs to (multi-central grouping).",
    )
    id: str
    name: str
    address: str | None = None
    device_name: str | None = None
    type: str | None = None
    description: str | None = Field(
        None, description="Optional human-readable message text."
    )
    priority: int | None = Field(
        None, description="Integer priority level (0 = normal)."
    )
    timestamp: AwareDatetime
    counter: int
    quittable: bool
    display_name: str | None = Field(
        None, description="Human-readable translation of the message code."
    )


class InstallModeInterfaceEntry(BaseModel):
    central: str | None = Field(None, description="CCU the interface belongs to.")
    interface: str = Field(
        ..., description="Interface ID the install-mode data point controls."
    )
    active: bool
    seconds: int = Field(
        ..., description="Remaining install-mode time (0 when inactive)."
    )
    observed: bool = Field(
        ..., description="False until the first state fetch succeeded."
    )


class InstallModeInterfaceRequest(BaseModel):
    interface: str
    active: bool
    seconds: int | None = Field(
        None, description="Install-mode duration; defaults to 60 when omitted.", ge=0
    )


class SystemUpdateEntry(BaseModel):
    central: str | None = Field(None, description="CCU this update info belongs to.")
    current_firmware: str | None = Field(
        None, description="Installed CCU firmware version."
    )
    available_firmware: str | None = Field(
        None, description="Installable CCU firmware version."
    )
    update_available: bool
    in_progress: bool = Field(
        ..., description="True while a system update is installing."
    )
    observed: bool = Field(
        ..., description="False until the first update-info fetch succeeded."
    )


class HubMetricsEntry(BaseModel):
    central: str | None = Field(None, description="CCU these metrics belong to.")
    system_health: float | None = Field(
        None,
        description="Aggregate health score in percent (0-100); omitted until observed.",
    )
    connection_latency_ms: float | None = Field(
        None, description="Average CCU round-trip latency; omitted until observed."
    )
    last_event_age_seconds: float | None = Field(
        None, description="Age of the newest backend event; omitted until observed."
    )


class ChannelLockRequest(BaseModel):
    enabled: bool = Field(
        ...,
        description="Include (true) / exclude (false) the channel from the week-program schedule.",
    )


class MasterProfileSummary(BaseModel):
    id: int
    name: str = Field(..., description="Localised profile name.")
    description: str = Field(..., description="Localised profile description.")
    param_count: int = Field(
        ..., description="Number of MASTER parameters this profile sets."
    )


class Params(BaseModel):
    constraint_type: str | None = Field(
        None, description='Usually "fixed"; other kinds appear sporadically.'
    )
    value: Any | None = None


class MasterProfile(BaseModel):
    id: int
    name: dict[str, str] = Field(
        ...,
        description='Locale-keyed profile name (e.g. `{"en": "Eco", "de": "Eco"}`).',
    )
    description: dict[str, str] = Field(
        ..., description="Locale-keyed profile description."
    )
    params: dict[str, Params] = Field(
        ..., description="MASTER parameter name to constraint."
    )


class InterfaceState(BaseModel):
    id: str
    name: str
    connected: bool
    interface: str
    central_id: str | None = None
    host: str | None = None
    note: str | None = None


class Room(BaseModel):
    name: str
    device_count: int


class Function(BaseModel):
    name: str
    device_count: int


class Channel(ChannelSummary):
    data_points: list[DataPointSummary] | None = Field(
        None, description="Present only with `?include=data_points`.\n"
    )


class DeviceChannel(BaseModel):
    device_address: str
    channels: list[Channel]


class Snapshot(BaseModel):
    generated_at: AwareDatetime
    devices: list[DeviceSummary]
    programs: list[ProgramSummary] | None = None
    sysvars: list[SysvarSummary] | None = None
    rooms: list[Room] | None = None
    functions: list[Function] | None = None
    interfaces: list[InterfaceState] | None = None
    device_channels: list[DeviceChannel] | None = Field(
        None,
        description="Present only when the request set `?include=channels` (or\n`data_points`). Nests each device's channels — and, with\n`data_points`, their data points — keyed by device address.\nParallel to `devices`, which stays unchanged.\n",
    )


class Role(StrEnum):
    admin = "admin"
    operator = "operator"
    viewer = "viewer"


class Scheme(StrEnum):
    basic = "basic"
    bearer = "bearer"
    session = "session"
    oidc = "oidc"


class Identity(BaseModel):
    subject: str
    role: Role
    scheme: Scheme | None = None


class UserListEntry(BaseModel):
    username: str
    role: Role


class TokenListEntry(BaseModel):
    id: str = Field(
        ...,
        description="Stable management identifier (16 hex chars from sha256 of the token).",
    )
    fingerprint: str = Field(
        ..., description="Last six characters of the token; full value is never exposed"
    )
    subject: str
    role: Role


class Query(BaseModel):
    address: str
    channel: int = Field(..., ge=0)
    parameter: str


class ValuesBatchRequest(BaseModel):
    queries: list[Query] = Field(..., max_length=1000)


class Result(BaseModel):
    address: str
    channel: int = Field(..., ge=0)
    parameter: str
    summary: DataPointSummary | None = None
    error: str | None = Field(
        None,
        description="Per-query failure. Set when `summary` is absent.\nStable values: `device not found`,\n`channel not found`, `parameter not found`,\n`parameter hidden`.\n",
    )


class ValuesBatchResponse(BaseModel):
    results: list[Result]


class CreateTokenResponse(BaseModel):
    id: str = Field(..., description="Stable management identifier.")
    token: str = Field(
        ..., description="Raw bearer token. URL-safe base64 (~43 chars)."
    )
    fingerprint: str
    subject: str
    role: Role


class MatterFabric(BaseModel):
    fabric_index: int = Field(
        ...,
        description="Stack-assigned fabric index per Matter Core Spec §11.18.5",
        ge=1,
        le=254,
    )
    fabric_id: int
    node_id: int
    vendor_id: int = Field(..., ge=0, le=65535)
    label: str | None = None
    compressed_id: str = Field(
        ..., description="8-byte compressed fabric identifier, hex-encoded"
    )
    root_public_key: str = Field(
        ...,
        description="Issuing root CA public key (uncompressed P-256, 65 bytes), hex-encoded",
    )


class MatterFabricList(BaseModel):
    fabrics: list[MatterFabric]


class MatterSetupPayload(BaseModel):
    discriminator: int = Field(..., ge=0, le=4095)
    passcode: int = Field(..., ge=1, le=99999998)
    vendor_id: int = Field(..., ge=0, le=65535)
    product_id: int = Field(..., ge=0, le=65535)
    qr_code: str = Field(
        ..., description="Onboarding payload prefixed with `MT:` per Matter §5.7.4"
    )
    manual_code: str = Field(
        ...,
        description="11-digit decimal code with Verhoeff check digit per Matter §5.1.4",
    )


class MatterCommissioningWindowRequest(BaseModel):
    duration_seconds: int | None = Field(
        None,
        description="Commissioning window duration in seconds. Default 900 (15 minutes).",
        ge=180,
        le=900,
    )


class MatterCommissioningWindowResponse(BaseModel):
    discriminator: int = Field(..., ge=0, le=4095)
    passcode: int = Field(..., ge=1, le=99999998)
    duration_seconds: int = Field(..., ge=180, le=900)
    qr_code: str
    manual_code: str


class MatterStatus(BaseModel):
    enabled: bool = Field(..., description="Bridge feature flag")
    listening: bool = Field(..., description="UDP listener bound")
    listen_addr: str | None = Field(None, description="Effective UDP listen address")
    endpoint_count: int = Field(
        ..., description="Bridged-endpoint count (excluding root)"
    )
    fabric_count: int = Field(..., description="Commissioned fabrics")
    enabled_count: int = Field(..., description="Allowlist entries with enabled=true")
    advertising: bool = Field(..., description="mDNS records emitted")
    commissioning_window_open: bool
    commissioning_window_duration_seconds: int | None = Field(None, ge=0, le=900)


class DpKind(StrEnum):
    custom = "custom"
    generic = "generic"
    calculated = "calculated"
    combined = "combined"
    measurement = "measurement"


class Mappable(StrEnum):
    mappable = "mappable"
    partially_mappable = "partially_mappable"
    unmappable = "unmappable"


class MatterExposure(BaseModel):
    central_name: str
    device_address: str
    channel_no: int
    dp_kind: DpKind
    dp_key: str
    parameter_label: str | None = Field(
        None,
        description="Ready-to-display caption for the data point behind\n`dp_key`: locale-aware channel-typed translation when one\nexists, otherwise the title-cased key. Same resolution as\n`DataPointSummary.parameter_label`.\n",
    )
    display_name: str | None = None
    enabled: bool
    friendly_name: str | None = None
    mappable: Mappable
    device_type: int | None = Field(None, ge=0, le=65535)
    clusters: list[int] | None = None
    reason: str | None = None


class MatterExposureList(BaseModel):
    items: list[MatterExposure]


class MatterExposureUpdate(BaseModel):
    central_name: str
    device_address: str
    channel_no: int
    dp_kind: DpKind
    dp_key: str
    enabled: bool
    friendly_name: str | None = None


class MatterExposureBulkUpdate(BaseModel):
    items: list[MatterExposureUpdate]


class UnIgnoreEntry(BaseModel):
    pattern: str
    updated_at: AwareDatetime | None = None
    updated_by: str | None = None


class Central1(BaseModel):
    central_name: str
    patterns: list[UnIgnoreEntry]


class UnIgnoreListResponse(BaseModel):
    centrals: list[Central1]


class UnIgnoreUpdateRequest(BaseModel):
    central_name: str
    patterns: list[str]


class UnIgnoreUpdateResponse(BaseModel):
    applied_count: int
    parse_errors: list[str] | None = None
    affected_devices: int | None = None
    patterns: list[UnIgnoreEntry] | None = None


class UnIgnoreCandidateList(BaseModel):
    candidates: list[str]
    include_master: bool | None = None


class Kind1(StrEnum):
    initial = "initial"
    change = "change"
    refresh = "refresh"


class WsEnvelope(BaseModel):
    seq: int = Field(
        ...,
        description='Monotonic, daemon-assigned sequence number. Strictly\nincreasing across the daemon\'s lifetime (resets to 0\non restart). Clients store the last received `seq` and\nreconnect with `{op:"subscribe", topics:[...], since:N}`\nto resume the stream.\n',
        ge=1,
    )
    kind: Kind1 = Field(
        ...,
        description="Event-family discriminator. `change` is the default\nand dominant case; `initial` is set on the first\nobservation of a data point (e.g. during cold-start\nreplay); `refresh` is reserved for periodic re-emits.\n",
    )
    topic: str | None = Field(
        None,
        description="Routing key the client subscribed to. Absent on command replies.",
    )
    type: str = Field(
        ..., description="Event-type discriminator (e.g. `datapoint.value_changed`)."
    )
    ts: AwareDatetime = Field(
        ..., description="RFC3339Nano timestamp (UTC) of when the event was emitted."
    )
    payload: Any = Field(..., description="One of the payload schemas listed below.")


class DataPointValueChangedPayload(BaseModel):
    central: str
    interface: str | None = None
    device_address: str
    channel: int = Field(..., ge=0)
    parameter: str
    paramset_key: str = Field(..., description="VALUES, MASTER, or LINK")
    unique_id: str = Field(
        ...,
        description="Canonical loom-namespaced routing key (`loom_<routing-key>`)\nfor this data point. Always present: the daemon owns the key and a\ncentral emits no events until its CCU serial (the central-id slot of\nthe key) is resolved by the bring-up readiness gate, so the value is\nnon-empty in normal operation (an empty string would signal an\nunresolved serial). Clients consume it directly instead of rebuilding\nfrom raw fields; see docs/external-clients/ha-unique-id-migration.md.\n",
    )
    value: Any = Field(
        ...,
        description="New value in its native CCU type (bool/int/float/string/list/null).",
    )
    previous: Any | None = Field(
        None,
        description='Prior value. Omitted when no prior value was tracked (initial\npush). Future revisions may surface a `kind: "initial"|"change"|"refresh"`\ndiscriminator on the envelope; see docs/external-clients/asks.md (B2).\n',
    )
    modified_at: AwareDatetime = Field(
        ..., description="RFC3339Nano timestamp the CCU observed the change at."
    )


class CustomDataPointStateChangedPayload(BaseModel):
    central: str
    device_address: str
    channel: int = Field(..., ge=0)
    name: str
    kind: str | None = Field(
        None,
        description="Widget hint matching CustomDPSummary.kind (e.g. `light`, `cover_blind`).",
    )
    unique_id: str = Field(
        ...,
        description="Canonical loom-namespaced routing key (`loom_<routing-key>`)\nfor this custom data point. Always present and non-empty — see\nDataPointValueChangedPayload.unique_id.\n",
    )
    state: dict[str, Any] = Field(
        ..., description="Composed state snapshot — keys depend on the CDP category."
    )


class CentralStateChangedPayload(BaseModel):
    central: str
    old_state: str
    new_state: str


class CentralReadinessChangedPayload(BaseModel):
    central: str
    phase: Phase
    ready: bool = Field(
        ...,
        description="True only once southbound bring-up has latched complete (phase == ready).",
    )
    interfaces_loaded: int = Field(..., ge=0)
    interfaces_total: int = Field(..., ge=0)


class SystemStatusChangedPayload(BaseModel):
    central: str
    component: str
    healthy: bool
    reason: str | None = None
    interface_id: str | None = None
    error_code: int | None = None
    central_state: str | None = Field(
        None, description="hmenum.CentralState string form"
    )
    connection_state: str | None = None
    client_state: str | None = Field(None, description="hmenum.ClientState string form")
    callback_state: str | None = None
    degraded_interfaces: list[str] | None = None
    issues: list[str] | None = None
    event_at: AwareDatetime


class SysvarChangedPayload(BaseModel):
    central: str
    name: str
    value_type: str | None = Field(
        None, description="hmenum.HubValueType (BOOL, FLOAT, INTEGER, STRING, …)."
    )
    unique_id: str = Field(
        ...,
        description="Canonical loom-namespaced routing key\n(`loom_<serial10>_sysvar_<hub-slug>`) for this sysvar. Always\npresent and non-empty — see DataPointValueChangedPayload.unique_id.\n",
    )
    value: Any = Field(..., description="New sysvar value in its native CCU type.")
    previous: Any | None = Field(
        None, description="Prior sysvar value; omitted when no prior value was tracked."
    )
    channel: str | None = Field(
        None,
        description='Canonical channel address ("ADDR:idx") of the device channel\nthis sysvar is associated with (explicit CCU assignment or\nname match — the same value the REST SysvarSummary carries).\nOmitted when the sysvar belongs to no device.\n',
    )
    device_address: str | None = Field(
        None,
        description='Device part of `channel` (before the ":"); omitted together\nwith `channel`.\n',
    )


class ProgramExecutedPayload(BaseModel):
    central: str
    program_id: str
    trigger: str | None = Field(
        None, description="hmenum.ProgramTrigger (MANUAL, SCHEDULE, EVENT, …)."
    )
    success: bool
    unique_id: str | None = Field(
        None,
        description="Canonical loom-namespaced routing key\n(`loom_<serial10>_program_<hub-slug(name)>`) for this program.\nOptional — omitted when the program name cannot be resolved;\nsee DataPointValueChangedPayload.unique_id.\n",
    )
    channel: str | None = Field(
        None,
        description='Canonical channel address ("ADDR:idx") of the device channel\nthis program is associated with (name match — the same value\nthe REST ProgramSummary carries). Omitted when the program\nbelongs to no device or is not yet loaded in the hub model.\n',
    )
    device_address: str | None = Field(
        None,
        description='Device part of `channel` (before the ":"); omitted together\nwith `channel`.\n',
    )


class InstallModeChangedPayload(BaseModel):
    central: str
    enabled: bool
    remaining_s: int = Field(
        ...,
        description="Seconds remaining before the pairing window closes; 0 when disabled.",
    )


class HubCountChangedPayload(BaseModel):
    central: str
    count: int


class HubMetricChangedPayload(BaseModel):
    central: str
    metric: str = Field(
        ...,
        description="Metric kind (system_health, connection_latency_ms, last_event_age_seconds).",
    )
    value: float
    unit: str | None = Field(
        None, description='Unit string ("%", "ms", "s"); omitted when unitless.'
    )


class HubConnectivityChangedPayload(BaseModel):
    central: str
    interface_id: str
    reachable: bool
    latency_ms: float | None = Field(
        None, description="Probe round-trip in milliseconds; omitted when not measured."
    )


class HubSystemUpdateChangedPayload(BaseModel):
    central: str
    current_firmware: str | None = Field(
        None, description="Installed firmware version; omitted while unobserved."
    )
    available_firmware: str | None = Field(
        None,
        description="Firmware version offered for install; omitted while unobserved.",
    )
    update_available: bool
    in_progress: bool


class OldState(StrEnum):
    disarmed = "disarmed"
    arming = "arming"
    armed = "armed"
    pending = "pending"
    triggered = "triggered"


class NewState(StrEnum):
    disarmed = "disarmed"
    arming = "arming"
    armed = "armed"
    pending = "pending"
    triggered = "triggered"


class Mode(StrEnum):
    disarmed = "disarmed"
    perimeter = "perimeter"
    full = "full"
    night = "night"
    vacation = "vacation"
    custom = "custom"


class AlarmStateChangedPayload(BaseModel):
    area_id: str
    area_name: str
    old_state: OldState
    new_state: NewState
    mode: Mode | None = Field(
        None, description="Active (or, while arming, target) protection mode."
    )
    changed_by: str | None = Field(
        None,
        description='Attribution (operator account, keypad identity, code name, or an engine-internal actor such as "engine:restore"); omitted when unattributed.',
    )
    source: str | None = Field(
        None,
        description="Surface the action came from (rest, ws, mqtt, hmcli, keypad, engine).",
    )
    incident_id: int | None = Field(
        None, description="References the active incident; omitted when none."
    )


class Kind2(StrEnum):
    exit_delay = "exit_delay"
    entry_delay = "entry_delay"


class AlarmCountdownPayload(BaseModel):
    area_id: str
    kind: Kind2
    remaining_s: int
    total_s: int
    remaining_ms: int = Field(
        ..., description="Remaining time in milliseconds (source fidelity)."
    )
    total_ms: int = Field(..., description="Total countdown length in milliseconds.")


class Mode1(StrEnum):
    perimeter = "perimeter"
    full = "full"
    night = "night"
    vacation = "vacation"
    custom = "custom"


class AlarmTriggeredPayload(BaseModel):
    area_id: str
    area_name: str
    incident_id: int
    sensor_id: str | None = Field(
        None,
        description="Triggering sensor id; omitted when the cause is not a sensor.",
    )
    sensor_name: str | None = None
    cause: str = Field(
        ...,
        description="Stable machine-readable cause token (sensor, adopted, central_lost, restored).",
    )
    mode: Mode1 | None = Field(
        None, description="Protection mode that was active at trigger time."
    )


class State(StrEnum):
    disarmed = "disarmed"
    arming = "arming"
    pending = "pending"
    triggered = "triggered"
    armed_home = "armed_home"
    armed_away = "armed_away"
    armed_night = "armed_night"
    armed_vacation = "armed_vacation"
    armed_custom_bypass = "armed_custom_bypass"


class AlarmPanelEntity(BaseModel):
    unique_id: str
    area_id: str
    name: str
    category: str
    state: State
    supported_modes: list[str] | None = None
    available: bool
    master: bool | None = None


class AlarmPanelChangedPayload(BaseModel):
    unique_id: str
    area_id: str
    name: str
    state: str
    available: bool
    removed: bool | None = None


class AlarmReminderPayload(BaseModel):
    area_id: str
    area_name: str | None = None
    mode: str = Field(
        ..., description="The protection mode the schedule expected the area to be in."
    )


class Class(StrEnum):
    arm = "arm"
    disarm = "disarm"
    trigger = "trigger"
    silence = "silence"
    bypass = "bypass"
    fault = "fault"
    test = "test"
    config = "config"


class AlarmJournalAppendedPayload(BaseModel):
    entry_id: int
    area_id: str | None = Field(None, description="Omitted for engine-global entries.")
    class_: Class = Field(..., alias="class")
    event: str = Field(
        ..., description="Stable machine-readable event token within the class."
    )
    actor: str | None = Field(
        None, description="Attribution; omitted when unattributed."
    )
    incident_id: int | None = Field(
        None, description="References the related incident; omitted when none."
    )


class AlarmWalkTestProgressPayload(BaseModel):
    area_id: str
    sensor_id: str
    sensor_name: str | None = None
    seen: int = Field(
        ...,
        description="Number of enrolled sensors that have reported an activation so far this session.",
    )
    total: int = Field(
        ..., description="Total number of sensors enrolled in the walk-test session."
    )


class AlarmHealthChangedPayload(BaseModel):
    healthy: bool
    note: str = Field(
        ..., description="Stable, English machine string describing the transition."
    )


class TriggeredEventSummary(BaseModel):
    parameter: str = Field(
        ..., description="Lowercased parameter name of the source that fired."
    )
    value: Any | None = Field(
        None, description="The value carried by the fire; omitted when none."
    )
    triggered_at: AwareDatetime | None = Field(
        None, description="RFC3339 timestamp of the fire."
    )


class EventGroupSummary(BaseModel):
    channel_address: str
    kind: str = Field(
        ...,
        description='Short device-trigger flavour ("keypress", "impulse", "device_error").',
    )
    event_types: list[str] = Field(
        ..., description="Lowercased member parameter names (event-type identifiers)."
    )
    parameters: list[str] = Field(
        ..., description="Upper-case CCU parameter names of the member sources."
    )
    available: bool
    last_triggered_event: TriggeredEventSummary | None = None
    unique_id: str = Field(
        ...,
        description="Canonical loom routing key for this event group — the same\nvalue the WS `hub.program_executed`-family event carries for\nevent groups. Lets clients build their entity registry from\nthe summary without recomputing the key. Always present and non-empty: a central serves no entity until its CCU serial (the central-id slot of the key) is resolved by the bring-up readiness gate.\n",
    )


class HubCountDataPoint(BaseModel):
    legacy_name: str
    value: int


class HubUpdateDataPoint(BaseModel):
    legacy_name: str
    update_available: bool
    in_progress: bool


class HubMetricDataPoint(BaseModel):
    legacy_name: str
    value: float
    unit: str | None = None


class HubConnectivityDataPoint(BaseModel):
    interface_id: str
    reachable: bool


class HubInstallModeDataPoint(BaseModel):
    interface_id: str
    enabled: bool
    remaining_s: int = Field(
        ..., description="Seconds left while enabled; 0 when disabled."
    )
    observed: bool = Field(
        ..., description="False until the first state has been read from the CCU."
    )


class HubDataPoints(BaseModel):
    central: str | None = None
    alarm_messages: HubCountDataPoint
    service_messages: HubCountDataPoint
    inbox: HubCountDataPoint
    update: HubUpdateDataPoint
    metrics: list[HubMetricDataPoint] | None = None
    connectivity: list[HubConnectivityDataPoint] | None = None
    install_mode: list[HubInstallModeDataPoint] | None = None


class DeviceCreatedPayload(BaseModel):
    central: str
    interface_id: str
    device_address: str
    model: str
    source: str | None = Field(
        None, description="hmenum.SourceOfDeviceCreation (CACHE, INIT, NEW_DEVICE, …)."
    )


class DeviceRemovedPayload(BaseModel):
    central: str
    interface_id: str
    device_address: str


class OptimisticRollbackPayload(BaseModel):
    central: str
    device_address: str
    channel: int = Field(..., ge=0)
    parameter: str
    paramset_key: str = Field(..., description="VALUES, MASTER, or LINK")
    reason: str = Field(
        ...,
        description="Why the optimistic value was rolled back (TTL expiry or CCU rejection).",
    )
    unique_id: str = Field(
        ...,
        description="Canonical loom-namespaced routing key (`loom_<routing-key>`)\nfor the rolled-back data point; matches the\n`datapoint.value_changed` entity key. Always present and\nnon-empty — see DataPointValueChangedPayload.unique_id.\n",
    )
    sent: Any | None = Field(
        None,
        description="The optimistic value that was rolled back. Omitted when not tracked.",
    )
    present: Any | None = Field(
        None,
        description="The value the data point reverted to (last CCU-confirmed value). Omitted when not tracked.",
    )


class DeviceTriggerPayload(BaseModel):
    central: str
    interface_id: str
    device_address: str
    channel: int = Field(..., ge=0)
    event_type: str
    parameter: str
    unique_id: str = Field(
        ...,
        description="Canonical loom-namespaced routing key (`loom_<routing-key>`)\nfor the data point this trigger fires on; matches the\n`datapoint.value_changed` entity key (a trigger and a value\nchange on the same DP route to the same entity). Always present\nand non-empty — see DataPointValueChangedPayload.unique_id.\n",
    )
    value: Any | None = Field(
        None,
        description="Optional value carried by the trigger event in its native CCU type. Omitted when absent.",
    )


class MatterCommissioningProgressPayload(BaseModel):
    stage: str = Field(
        ...,
        description="Stage label (e.g. `pase_session_open`, `add_noc`, `case_session_first`).",
    )
    message: str | None = Field(
        None, description="Human-readable detail; may be empty."
    )


class MatterFabricRemovedPayload(BaseModel):
    fabric_index: int = Field(
        ...,
        description="Stack-assigned fabric index of the removed fabric.",
        ge=1,
        le=254,
    )


class MatterEndpointAssembledPayload(BaseModel):
    endpoint_count: int = Field(
        ...,
        description="Number of endpoints in the assembled topology, including the root + Aggregator.",
        ge=0,
    )


class Class1(StrEnum):
    basic = "basic"
    expert = "expert"
    secret = "secret"


class SchemaField(BaseModel):
    path: str = Field(
        ..., description='Dot-separated field path, e.g. "north.rest.listen".'
    )
    class_: Class1 = Field(
        ...,
        alias="class",
        description="Visibility class from the cfg struct tag. `basic` fields are\nshown in the default UI view; `expert` requires the expert\ntoggle; `secret` values are always redacted in responses.\n",
    )
    go_type: str = Field(
        ...,
        description='Go type name for the field (e.g. "string", "bool", "int", "time.Duration").',
    )
    restart_required: bool = Field(
        ...,
        description="Whether changing this field requires a daemon restart to take effect.",
    )
    default: Any | None = Field(
        None,
        description="The consumer-facing default value for this field, as emitted by\nthe schema handler. Type follows the field's `go_type` (string,\nbool, number, …); absent when the field has no documented default.\n",
    )


class SchemaResponse(BaseModel):
    sections: list[str] = Field(
        ...,
        description='Top-level config section names (e.g. ["logging", "north", "centrals"]).',
    )
    fields: list[SchemaField]


class Sources(StrEnum):
    bootstrap = "bootstrap"
    db = "db"
    env = "env"
    default = "default"


class ConfigSnapshotResponse(BaseModel):
    config: dict[str, Any] = Field(
        ...,
        description='Full effective config tree with secret fields replaced by\n"***". Shape mirrors the daemon\'s Config struct.\n',
    )
    sources: dict[str, Sources] = Field(
        ...,
        description="Map from dot-separated config path to the layer that supplied\nthe value. Known layers: bootstrap (YAML file), db (SQLite),\nenv (environment variable), default (hardcoded default).\n",
    )


class Role4(StrEnum):
    viewer = "viewer"
    operator = "operator"
    admin = "admin"


class UserCreate(BaseModel):
    username: str = Field(..., description="Login name; must be unique.")
    password: str = Field(
        ..., description="Plaintext password; the daemon hashes it before storage."
    )
    role: Role4


class UserUpdate(BaseModel):
    password: str | None = Field(
        None, description="New plaintext password. Omit to leave unchanged."
    )
    role: Role4 | None = Field(None, description="New role. Omit to leave unchanged.")


class UserSummary(BaseModel):
    subject: str = Field(..., description="Login name / stable identity key.")
    role: Role4
    created_at: AwareDatetime
    last_seen_at: AwareDatetime | None = Field(
        None,
        description="Last successful authentication time. Absent when never authenticated.",
    )


class TokenCreate(BaseModel):
    subject: str = Field(
        ...,
        description='Logical owner of the token (e.g. "homeassistant", "ci-runner").',
    )
    role: Role4
    expires_in_days: int | None = Field(
        None,
        description="Optional token lifetime in days. When set and positive, the token\nis rejected after this many days. Omitted or non-positive creates a\ntoken that never expires.\n",
        ge=1,
    )


class TokenCreated(BaseModel):
    token: str = Field(
        ...,
        description="Raw bearer token. URL-safe base64. Shown EXACTLY ONCE — store it immediately.",
    )
    fingerprint: str = Field(
        ...,
        description="Stable opaque identifier derived from the token (sha256-based).",
    )
    expires_at: AwareDatetime | None = Field(
        None, description="Expiry instant. Absent when the token never expires."
    )


class TokenSummary(BaseModel):
    fingerprint: str = Field(
        ..., description="Stable opaque identifier used as the delete key."
    )
    subject: str
    role: Role4
    created_at: AwareDatetime
    last_seen_at: AwareDatetime | None = Field(
        None, description="Last successful authentication time. Absent when never used."
    )
    expires_at: AwareDatetime | None = Field(
        None, description="Expiry instant. Absent when the token never expires."
    )


class RpcType(StrEnum):
    field_ = ""
    xmlrpc = "xmlrpc"
    binrpc = "binrpc"
    jsonrpc = "jsonrpc"


class InterfaceSpec(BaseModel):
    name: str = Field(
        ...,
        description='Homematic interface identifier, e.g. "HmIP-RF", "BidCos-RF", "CUxD".',
    )
    port: int | None = Field(
        None,
        description='Overrides the default XML-RPC/BIN-RPC port. 0 or absent means "use backend default".',
        ge=0,
        le=65535,
    )
    remote_path: str | None = Field(
        None,
        description='URL path override for XML-RPC requests. Empty means "use backend default".',
    )
    rpc_type: RpcType | None = Field(
        None,
        description='Transport selector. Empty means "derive from interface name".',
    )


class VisibilityConfig(BaseModel):
    un_ignore: list[str] | None = Field(
        None,
        description="MODEL:CHANNEL:PARAMETER patterns (with `*` wildcards) that\npromote parameters from the default-hidden set into the\nvisible data-point surface. Bare parameter names are\ntreated as *:*:PARAMETER.\n",
    )


class SysvarMarker(StrEnum):
    HAHM = "HAHM"
    HX = "HX"
    INTERNAL = "INTERNAL"
    MQTT = "MQTT"


class ProgramMarker(StrEnum):
    HAHM = "HAHM"
    HX = "HX"
    INTERNAL = "INTERNAL"
    MQTT = "MQTT"


class CentralBehavior(BaseModel):
    light_last_brightness: bool | None = Field(
        None,
        description="Restore last non-zero brightness on a plain light turn-on (default true); false turns on at full.",
    )
    use_group_channel_for_cover_state: bool | None = Field(
        None,
        description="Report cover position from the group channel when present (default true).",
    )
    enable_sysvar_scan: bool | None = Field(
        None, description="Scan system variables into the hub layer (default true)."
    )
    enable_program_scan: bool | None = Field(
        None, description="Scan programs into the hub layer (default true)."
    )
    include_internal_sysvars: bool | None = Field(
        None, description="Include CCU-internal system variables (default true)."
    )
    include_internal_programs: bool | None = Field(
        None, description="Include CCU-internal programs (default false)."
    )
    sysvar_markers: list[SysvarMarker] | None = Field(
        None,
        description="Restrict the sysvar scan to entities whose CCU description starts with one of these markers. Empty includes everything that passes the internal filter.",
    )
    program_markers: list[ProgramMarker] | None = Field(
        None, description="Program-scan equivalent of sysvar_markers."
    )
    sysvar_scan_interval: int | None = Field(
        None,
        description="Periodic sysvar-refresh cadence as a Go time.Duration (nanoseconds). 0 = compiled-in default (5m).",
    )
    enable_device_firmware_check: bool | None = Field(
        None,
        description="Surface per-device firmware-update entities (default true — a deliberate divergence from the reference stack's false default).",
    )
    delay_new_device_creation: bool | None = Field(
        None,
        description="Defer ingest of a newly-paired device to the inbox/manual-accept flow (default false).",
    )


class ScheduleChannelRef(BaseModel):
    address: str
    number: int
    device_address: str


class ClimatePeriod(BaseModel):
    start_time: str = Field(..., description="HH:MM start of the period.")
    end_time: str = Field(..., description="HH:MM end of the period.")
    temperature: float = Field(..., description="Setpoint for the period.")


class ClimateWeekday(BaseModel):
    base_temperature: float
    periods: list[ClimatePeriod]


class ClimateProfile(BaseModel):
    weekdays: dict[str, ClimateWeekday]


class SimpleScheduleEntry(BaseModel):
    slot_no: int
    weekdays: list[str]
    time: str
    condition: str | None = None
    astro_type: str | None = None
    astro_offset_minutes: int | None = None
    target_channels: list[str] | None = None
    level: float
    level_2: float | None = None
    duration: str | None = None
    ramp_time: str | None = None
    lock_mode: str | None = None
    lock_action: str | None = None
    permission: str | None = None


class Kind3(StrEnum):
    climate = "climate"
    simple = "simple"


class Schedule(BaseModel):
    channel: ScheduleChannelRef
    kind: Kind3
    domain: str | None = None
    active_profile: str | None = None
    active_profile_index: int | None = None
    profiles: dict[str, ClimateProfile] | None = None
    simple_entries: list[SimpleScheduleEntry] | None = None


class SetActiveProfileRequest(BaseModel):
    profile: str


class CopyScheduleRequest(BaseModel):
    target_device_address: str


class CopyProfileRequest(BaseModel):
    source_profile: int = Field(..., ge=1, le=6)
    target_channel_address: str
    target_profile: int = Field(..., ge=1, le=6)


class ScheduleType(StrEnum):
    default = "default"
    climate = "climate"


class ChannelType(StrEnum):
    primary = "primary"
    secondary = "secondary"


class TargetChannelSummary(BaseModel):
    channel_no: int
    channel_address: str
    name: str
    channel_type: ChannelType
    unique_id: str = Field(
        ...,
        description='Canonical loom-namespaced routing key for the schedule-channel-switch\nentity this target maps to\n(`loom_schedule_channel_switch_<device-addr>_schedule_channel_lock_<channel_key>`),\nbuilt over the owning device address + parameter\n"SCHEDULE_CHANNEL_LOCK_<channel_key>" (the map key, e.g. "1_1") +\nprefix "schedule_channel_switch". Bit-identical to the\nclient-synthesised key; always present and non-empty.\n',
    )


class Link(BaseModel):
    sender_address: str
    receiver_address: str
    name: str | None = None
    description: str | None = None
    flags: int | None = None
    sender_device_name: str | None = None
    sender_device_model: str | None = None
    sender_channel_type: str | None = None
    sender_channel_type_label: str | None = None
    sender_channel_name: str | None = None
    receiver_device_name: str | None = None
    receiver_device_model: str | None = None
    receiver_channel_type: str | None = None
    receiver_channel_type_label: str | None = None
    receiver_channel_name: str | None = None
    peer_address: str
    peer_device_name: str | None = None
    peer_device_model: str | None = None
    direction: str


class AddLinkRequest(BaseModel):
    sender_address: str
    receiver_address: str
    name: str | None = None
    description: str | None = None


class CentralLinksStatus(BaseModel):
    supported: bool
    reason: str | None = None
    eligible_channels: int | None = None


class CalculatedDPSummary(BaseModel):
    name: str
    category: str | None = None
    value: Any
    observed: bool
    translated_name: str | None = Field(
        None,
        description="Locale-aware per-entity name, resolved through the same\nchain as generic data points (channel-typed translation →\nbare-parameter translation → title-cased parameter). Lets\nclients spawn calculated/combined entities with the same\nnames the reference stack generates.\n",
    )
    modified_at: AwareDatetime | None = None
    unique_id: str = Field(
        ...,
        description="Canonical loom routing key for this calculated data point —\nthe same canonical key generic data points carry. Lets\nclients build their entity registry from the summary without\nrecomputing the key. Always present and non-empty: a central serves no entity until its CCU serial (the central-id slot of the key) is resolved by the bring-up readiness gate.\n",
    )


class CalculatedDPDetail(CalculatedDPSummary):
    depends_on: list[str] | None = None


class BackupEntry(BaseModel):
    id: str
    central: str
    bytes: int
    created_at: AwareDatetime


class EditSessionResponse(BaseModel):
    token: str
    key: str
    subject: str | None = None
    expires: AwareDatetime


class FunctionEntry(BaseModel):
    name: str
    device_count: int


class Incident(BaseModel):
    id: str
    when: AwareDatetime
    component: str
    severity: str
    summary: str
    detail: str | None = None


class InboxDevice(BaseModel):
    central: str | None = Field(
        None, description="CCU that reported this pending device."
    )
    address: str
    model: str
    serial: str | None = None
    manufacturer: str | None = None
    first_seen: int | None = None


class LinkableChannel(BaseModel):
    address: str
    channel_type: str | None = None
    channel_type_label: str | None = None
    channel_name: str | None = None
    device_address: str
    device_name: str | None = None
    device_model: str | None = None


class LogRecord(BaseModel):
    seq: int
    time: AwareDatetime
    level: str
    logger: str | None = None
    msg: str
    attrs: dict[str, Any] | None = None


class RPCRecordingStatus(BaseModel):
    central: str
    active: bool
    entries: int
    ends_at: str | None = None
    randomize: bool | None = None


class RoomEntry(BaseModel):
    name: str
    device_count: int


class AlarmAreaConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class AlarmArea(BaseModel):
    id: str
    name: str
    position: int | None = Field(
        None, description="Display ordering hint for the SPA area list."
    )
    config: AlarmAreaConfig | None = None


class Type1(StrEnum):
    door = "door"
    window = "window"
    motion = "motion"
    tamper = "tamper"
    hazard = "hazard"
    panic = "panic"


class AlarmSensor(BaseModel):
    id: str
    central: str = Field(..., description="Owning CCU (central name).")
    interface_id: str
    channel_address: str
    parameter: str
    type: Type1 = Field(
        ..., description="Sensor role; presets the mode matrix and behaviour flags."
    )
    name: str | None = None
    config: dict[str, Any] | None = Field(
        None,
        description="Engine-owned per-sensor configuration document (mode matrix, entry-delay flag, bypass eligibility, …).",
    )


class Class2(StrEnum):
    acoustic_siren = "acoustic_siren"
    switched_siren = "switched_siren"
    smoke_sounder = "smoke_sounder"
    optical_siren = "optical_siren"
    alarm_light = "alarm_light"
    chirp = "chirp"
    notification = "notification"
    sysvar_mirror = "sysvar_mirror"


class AlarmOutput(BaseModel):
    id: str
    class_: Class2 = Field(
        ...,
        alias="class",
        description="Output driver class. The class, not the backing device type, decides which safety invariants apply.",
    )
    central: str = Field(..., description="Owning CCU (central name).")
    channel_address: str
    name: str | None = None
    config: dict[str, Any] | None = Field(
        None,
        description="Engine-owned per-output configuration document (per-mode assignment, indoor/outdoor flag, duration/tone, …).",
    )


class AlarmModeReadiness(BaseModel):
    ready: bool = Field(
        ..., description="True when the mode can be armed without `force`."
    )
    blockers: list[str] | None = Field(
        None, description="Sensor ids currently blocking the arm into this mode."
    )
    warnings: list[str] | None = Field(
        None, description="Sensor ids with non-blocking health warnings for this mode."
    )


class State1(StrEnum):
    disarmed = "disarmed"
    arming = "arming"
    armed = "armed"
    pending = "pending"
    triggered = "triggered"


class Mode2(StrEnum):
    disarmed = "disarmed"
    perimeter = "perimeter"
    full = "full"
    night = "night"
    vacation = "vacation"
    custom = "custom"


class Incident1(BaseModel):
    id: str | None = None
    silenced: bool | None = None


class Kind4(StrEnum):
    exit_delay = "exit_delay"
    entry_delay = "entry_delay"


class Countdown(BaseModel):
    kind: Kind4 | None = None
    remaining_s: int | None = None
    total_s: int | None = None


class AlarmAreaStatus(BaseModel):
    id: str
    name: str
    state: State1 = Field(
        ..., description="Arm-state-machine state (docs/alarm-concept.md §5)."
    )
    mode: Mode2 | None = Field(
        None, description="Currently active (or, while arming, target) protection mode."
    )
    bypassed: list[str] | None = Field(
        None, description="Sensor ids currently bypassed for the active/pending arm."
    )
    incident: Incident1 | None = Field(
        None,
        description="The area's open incident, present only while `state` is `triggered`.",
    )
    countdown: Countdown | None = Field(
        None,
        description="A running exit/entry delay countdown, present only while one is active.",
    )
    readiness: dict[str, AlarmModeReadiness] | None = Field(
        None, description="Per-mode arming readiness, keyed by mode name."
    )
    walktest_active: bool = Field(
        ..., description="True while a walk-test session is running on this area."
    )


class Mode3(StrEnum):
    perimeter = "perimeter"
    full = "full"
    night = "night"
    vacation = "vacation"
    custom = "custom"


class AlarmArmRequest(BaseModel):
    mode: Mode3 = Field(..., description="Target protection mode.")
    force: bool | None = Field(
        None,
        description="Arm despite readiness blockers, where the engine's blocker policy allows overriding.",
    )
    skip_delay: bool | None = Field(
        None, description="Skip the configured exit delay and arm immediately."
    )
    bypass: list[str] | None = Field(
        None, description="Sensor ids to bypass for this arm attempt."
    )
    code: str | None = Field(
        None,
        description="Alarm code supplied with the arm, when the area's code policy requires one (or to surface a duress code). Never logged or persisted in cleartext.\n",
    )


class AlarmVerbRequest(BaseModel):
    code: str | None = Field(
        None,
        description="Alarm code for the verb, when the area's code policy requires one. Never logged or persisted in cleartext.\n",
    )


class AlarmCodePerms(BaseModel):
    arm: bool
    disarm: bool
    silence: bool


class Kind5(StrEnum):
    pin = "pin"
    keypad_slot = "keypad_slot"
    remote_key = "remote_key"


class AlarmCode(BaseModel):
    id: str
    name: str
    kind: Kind5 = Field(..., description="Code class.")
    duress: bool | None = Field(
        None,
        description="A PIN that disarms normally but fires a silent duress alarm. Only meaningful for the pin kind.\n",
    )
    perms: AlarmCodePerms
    areas: list[str] | None = Field(
        None, description="Restrict to these area ids; empty means every area."
    )
    binding: Any | None = Field(
        None,
        description="Engine-owned hardware-binding document for the keypad_slot / remote_key kinds; absent for pin codes.\n",
    )
    valid_from_ms: int | None = Field(
        None, description="Optional validity-window start (Unix ms); 0 leaves it open."
    )
    valid_until_ms: int | None = Field(
        None, description="Optional validity-window end (Unix ms); 0 leaves it open."
    )
    enabled: bool
    created_ms: int | None = None
    updated_ms: int | None = None


class AlarmCodeRequest(BaseModel):
    name: str
    kind: Kind5
    pin: str | None = Field(
        None,
        description="Cleartext code, write-only, for the pin kind. Omitted on update to keep the existing hash.\n",
    )
    duress: bool | None = None
    perms: AlarmCodePerms
    areas: list[str] | None = None
    binding: Any | None = Field(
        None,
        description="Engine-owned hardware-binding document (keypad_slot / remote_key).",
    )
    valid_from_ms: int | None = None
    valid_until_ms: int | None = None
    enabled: bool


class State2(StrEnum):
    arming = "arming"
    armed = "armed"


class AlarmArmAccepted(BaseModel):
    state: State2 = Field(..., description="Resulting area state.")
    bypassed: list[str] | None = Field(
        None, description="Sensor ids actually bypassed for this arm."
    )
    exit_delay_s: int | None = Field(
        None,
        description="Exit delay in seconds the area is now counting down; 0 when armed immediately.",
    )


class Class3(StrEnum):
    arm = "arm"
    disarm = "disarm"
    trigger = "trigger"
    silence = "silence"
    bypass = "bypass"
    fault = "fault"
    test = "test"
    config = "config"


class AlarmJournalEntry(BaseModel):
    id: int
    when: AwareDatetime
    area_id: str
    class_: Class3 = Field(
        ...,
        alias="class",
        description="Journal bucket used by the `class` query filter.",
    )
    event: str = Field(
        ...,
        description='Stable machine-readable event token within the class (e.g. "armed", "force_armed", "silenced").',
    )
    actor: str | None = Field(
        None,
        description="Identity that caused the entry (operator account, keypad identity, code name, or an engine-internal actor); empty when unattributed.",
    )
    source: str | None = Field(
        None,
        description="Surface the action came from (rest, ws, mqtt, hmcli, keypad, engine).",
    )
    incident_id: int | None = Field(
        None,
        description="Linked incident id, present when the entry belongs to a trigger episode.",
    )
    details: dict[str, Any] | None = Field(
        None, description="Engine-owned, event-class-specific detail document."
    )


class Sensor(BaseModel):
    id: str
    name: str | None = None
    tested: bool = Field(
        ...,
        description="True once this sensor reported at least one activation during the current session.",
    )
    last_triggered_at: AwareDatetime | None = None


class AlarmWalkTestStatus(BaseModel):
    active: bool
    started_at: AwareDatetime | None = None
    sensors: list[Sensor] = Field(
        ...,
        description="One row per sensor enrolled in the area, tracking walk-test coverage.",
    )


class AlarmOutputTestRequest(BaseModel):
    optical_only: bool | None = Field(
        None,
        description="Fire only the output's optical/visual indication, suppressing sound. Ignored for outputs with no audible element.",
    )


class DeviceDetail(DeviceSummary):
    firmware: Firmware
    availability: Availability
    channels: list[ChannelSummary]


class AlarmReadinessChangedPayload(BaseModel):
    area_id: str
    readiness: dict[str, AlarmModeReadiness] = Field(
        ..., description="Per-mode arming readiness, keyed by mode name."
    )


class CentralRow(BaseModel):
    name: str = Field(
        ...,
        description="Daemon-local identifier; must be unique. This is the\ncanonical central-scope discriminator: guaranteed equal to\n`SystemCCUEntry.name` and to the `central` field in\nWS / payload envelopes (`name == SystemCCUEntry.name ==\npayload.central`). Changing it re-scopes every per-central\nrequest, subscription and payload for this CCU.\n",
    )
    host: str = Field(..., description="CCU hostname or IP address.")
    serial: str | None = Field(
        None,
        description='CCU hardware serial, set when the central is adopted from SSDP/UPnP discovery. Empty for YAML / manually-entered rows. Lets discovery mark a CCU "already configured" by serial regardless of its host.',
    )
    port: int | None = Field(
        None,
        description="Legacy single-port override applied to all interfaces when ports map is absent.",
        ge=0,
        le=65535,
    )
    json_rpc_port: int | None = Field(
        None,
        description="HTTP port for JSON-RPC and web endpoints. 0 defaults to 80 (plain) / 443 (TLS).",
        ge=0,
        le=65535,
    )
    username: str | None = None
    password_env: str | None = Field(
        None,
        description="Environment variable name whose value is the CCU password (preferred).",
    )
    password_plain: str | None = Field(
        None,
        description="Plaintext password fallback. Only populated when\nallow_plaintext_secrets is enabled.\n",
    )
    tls: bool | None = None
    tls_insecure_skip_verify: bool | None = None
    primary_interface: str | None = Field(
        None,
        description="Pins the primary interface for health aggregation. Empty uses the HmIP-RF heuristic.",
    )
    interfaces: list[InterfaceSpec] = Field(
        ..., description="At least one interface must be listed."
    )
    ports: dict[str, int] | None = Field(
        None,
        description="Per-interface port overrides; keys are interface name strings.",
    )
    visibility: VisibilityConfig | None = None
    behavior: CentralBehavior | None = None
    enabled: bool = Field(
        ..., description="Whether the daemon should connect to this CCU at startup."
    )
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class WeekProfileResponse(BaseModel):
    address: str
    unique_id: str = Field(
        ...,
        description='Canonical loom-namespaced routing key for the device-level\nweek-profile sensor entity\n(`loom_week_profile_<device-addr>_week_profile`), built over the\nowning device address + parameter "WEEK_PROFILE" + prefix\n"week_profile". Bit-identical to the client-synthesised key so the\nclient consumes it instead of recomputing it. Always present and\nnon-empty (the serial-readiness gate guarantees the central-id slot).\n',
    )
    schedule_type: ScheduleType
    min_temp: float
    max_temp: float
    profile_count: int
    current_profile: str | None = None
    available_profiles: list[str] | None = None
    schedule_enabled: dict[str, bool] | None = None
    available_target_channels: dict[str, TargetChannelSummary] | None = Field(
        None,
        description='Maps each channel-lock key (e.g. "1_1") to the actuator channel it controls, so a per-channel schedule switch can be named after that channel without re-deriving the channel-group layout.',
    )
    has_climate_schedule: bool
